# Dockerfile.node
FROM node:20 AS node-builder

WORKDIR /app

# Copy package files and install deps
COPY package.json ./
RUN npm install

# Copy source files
COPY . .

# Build TypeScript
RUN npm run build

FROM node:20

WORKDIR /app

# Copy built dist
COPY --from=node-builder /app/dist ./dist
COPY --from=node-builder /app/package.json ./

COPY --from=node-builder /app/src ./src  

RUN npm install --omit=dev   # runtime deps only

EXPOSE 4000

ENV PORT=4000
ENV ZINGO_CLI_PATH=/usr/local/bin/zingo-cli
ENV ZINGO_DATA_DIR=/data

# RUN npm install -g ts-node typescript
# CMD ["ts-node", "src/server.ts"]

CMD ["node", "dist/server.js"]
